# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testnbdev1',
                'doc_host': 'https://chrphb.github.io',
                'git_url': 'https://github.com/chrphb/testnbdev1',
                'lib_path': 'testnbdev1'},
  'syms': {'testnbdev1.core': {'testnbdev1.core.foo': ('core.html#foo', 'testnbdev1/core.py')}}}
